### ISSUE TITLE
FilledGeometry and palleted plugin

### ISSUE THREAD

**Issue by ghost** [eXponenta/pixi5-svg#2]
I really like the quality of rendered SVGs on the demo https://exponenta.github.io/pixi5-svg-examples/live.html, but can't for the life of me find any documentation on the palleted plugin. 

The graphics I render are much less crisp than the demo – with FilledGeometry in demo:
![withFilledGeometry](https://user-images.githubusercontent.com/19517080/82726700-6bca9280-9cab-11ea-990c-598ab7787256.JPG)

Without FilledGeometry on my local project:
![withoutFilledGeometry](https://user-images.githubusercontent.com/19517080/82726726-9c123100-9cab-11ea-8f20-d1810428ab5d.JPG)

If there is any documentation / library that would give more info on the pallete plugin?

**Comment by ghost** [comment]
For me, this issue in quality was caused by my use of the AdjustmentFilter. Any more info on the pallete plugin would be helpful though if it exists

**Comment by eXponenta** [comment]
Palette mode store data values in pallette texture.
It required for fast colors changing of shape. When it not required - y may not use it.

**Comment by ghost** [comment]
Is there a link to the plugin / api?
